language: php

git:
  depth: false

env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

matrix:
  include:
    - dist: precise
      php: '5.4'
      env: SONAR_SCANNER=false
    - dist: xenial
      php: '7.2'
      env: SONAR_SCANNER=true

services:
  - redis-server

install:
  - composer install --prefer-source --no-interaction
  - composer update
  - composer dumpautoload

script:
  - vendor/bin/phpcs --ignore=functions.php --standard=PSR2 src/
  - vendor/bin/phpunit -c phpunit.xml.dist -v --testsuite integration
  - 'if [ "$SONAR_SCANNER" == "true" ]; then bash sonar-scanner.sh; fi'
