language: php

matrix:
  include:
    - dist: precise
      php: '5.3'
    - dist: trusty
      php: '7.3'

services:
  - redis-server

install:
  - composer install --prefer-source --no-interaction
  - composer update
  - composer dumpautoload

script:
  - vendor/bin/phpcs --ignore=functions.php --standard=PSR2 src/
  - vendor/bin/phpunit -c phpunit.xml.dist -v --testsuite integration
